all:
  vars:
    control_plane_endpoint: 10.0.60.100
    load_balancer_ip_pool:
      - 10.0.60.224/27
metal:
  children:
    masters:
      hosts:
        luigi:
          {
            ansible_host: 10.0.50.131,
            mac: "6C:4B:90:60:29:C4",
            disk: sda,
            network_interface: eno1,
          }
        peach:
          {
            ansible_host: 10.0.50.132,
            mac: "6C:4B:90:5F:8E:43",
            disk: sda,
            network_interface: eno1,
          }
        toad:
          {
            ansible_host: 10.0.50.133,
            mac: "6C:4B:90:5B:A3:56",
            disk: sda,
            network_interface: eno1,
          }
    workers:
      hosts:
        yoshi:
          {
            ansible_host: 10.0.50.134,
            mac: "6C:4B:90:5B:6E:6D",
            disk: sda,
            network_interface: eno1,
          }
